spring:
  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update  
  datasource:
    platform: postgress
    url: jdbc:postgresql://ec2-107-22-241-205.compute-1.amazonaws.com:5432/da72h6807f6fbs
    username: adsrbnorhsljlp
    password: 58295c0cd0eddd49bcac581511095fc407fae364f065141824ee7aa5e2e27e18

aws:
  bucket: senhas
  secretKey: ${secretKey}
  accessKey: ${accessKey}
  region: us-east-2
  endpointUrl: https://senhas.s3.us-east-2.amazonaws.com/
#  https://s3.aws.amazon.com
  