spring:
  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update  
  datasource:
    platform: postgress
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

aws:
  bucket: senhas
  secretKey: ${secretKey}
  accessKey: ${accessKey}
  region: us-east-2
  endpointUrl: https://senhas.s3.us-east-2.amazonaws.com/
#  https://s3.aws.amazon.com
  